server:
  port: ${APP_PORT:8080}
spring:
  application:
    name: "api-ai-finance"
  webflux:
    base-path: ${APP_CONTEXT:/api-ai-finance}
  devtools:
    add-properties: false
management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true