apply plugin: 'org.springframework.boot'

dependencies {
	implementation project(':reactive-web')
    implementation project(':model')
    implementation project(':usecase')
    implementation 'org.springframework.boot:spring-boot-starter'
    runtimeOnly('org.springframework.boot:spring-boot-devtools')
    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
    testImplementation 'tools.jackson.core:jackson-databind'
    implementation("org.springframework.boot:spring-boot-starter-actuator:${springBootVersion}")
    implementation("io.micrometer:micrometer-core:1.17.0-M1")
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar {
    // To disable the *-plain.jar
    enabled = false
}

bootJar {
    // Sets output jar name
    archiveFileName = "${project.getParent().getName()}.${archiveExtension.get()}"
}

bootRun {
    jvmArgs = ['--enable-native-access=ALL-UNNAMED']
}
